const os = require('os');
console.log("Freememory:", os.freemem());
console.log("homedir:", os.homedir());
console.log("hostname:", os.hostname());
console.log("endianness:", os.endianness());
console.log("loadavg:", os.loadavg());
console.log("platform:", os.platform());
console.log("release:", os.release());
console.log("tmpdir:", os.tmpdir());
console.log("totalmem:", os.totalmem());
console.log("type:", os.type());
console.log("uptime:", os.uptime());